In [70]:
#importamos librerias de pandas para manipular datos
import pandas as pd 
import numpy as np

In [71]:
df_base = pd.read_csv('Dataset_España.csv', sep=';')
df_base

,fecha_albaran,codigo_cliente,codigo_articulo,unidades,precio,precio_coste,importe_coste,importe_bruto,importe_neto,importe_liquido,...,mes,semana_anio,trimestre,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz,anio_semana
0,2021-08-13,10669,813-002,20.0,1.000,0.2732,5.4635,20.00,20.00,22.9900,...,8,32,3,10669,ESPAÑA,MALAGA,MALAGA,UE,Cruz3,2021-32
1,2022-07-13,17128,890-122,2.0,1.000,0.1012,0.2024,2.00,2.00,2.4200,...,7,28,3,17128,ESPAÑA,BURGOS,BURGOS,UE,CruzND,2022-28
2,2020-09-24,50017,813-351,2.0,1.280,0.3002,0.6004,2.56,2.56,3.0976,...,9,39,3,50017,ESPAÑA,BARCELONA,BARCELONA,UE,UsuarioRK,2020-39
3,2020-07-14,50010,813-351,4.0,1.280,0.2903,1.1613,5.12,5.12,6.1952,...,7,29,3,50010,ESPAÑA,BARCELONA,BARCELONA,UE,UsuarioRK,2020-29
4,2024-01-15,60000,012-086,1.0,1.612,0.0366,0.0366,1.61,1.61,1.9481,...,1,3,1,60000,ESPAÑA,NaN,NaN,UE,UsuarioCR,2024-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597366,2022-03-01,11117,925-773,1.0,123.926,29.4304,29.4304,123.93,57.01,68.9821,...,3,9,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2022-9
597367,2020-02-06,11117,924-602,1.0,123.967,32.6790,32.6790,123.97,57.03,69.0063,...,2,6,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2020-6
597368,2021-09-21,11117,923-307,1.0,126.405,29.8093,29.8093,126.41,58.15,70.3615,...,9,38,3,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2021-38
597369,2021-06-11,11117,923-306,1.0,126.405,30.0177,30.0177,126.41,58.15,70.3615,...,6,23,2,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2021-23
597370,2021-04-23,11117,909-153,1.0,227.273,65.0035,65.0035,227.27,104.54,126.4934,...,4,16,2,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2021-16

In [72]:
df_base=df_base.drop(columns=['precio', 'precio_coste', 'importe_coste', 'importe_bruto',
       'importe_neto', 'importe_liquido', 'base_imponible', 'por_descuento',
       'por_descuento2', 'por_margen_beneficio', 'margen_beneficio',
       'por_margen_calc', 'margen_calc'])

In [73]:

df_base=df_base[df_base['anio']>=2022]
df_base

,fecha_albaran,codigo_cliente,codigo_articulo,unidades,tipo_abc,agrupacion_listado,agrupacion_canal,anio,mes,semana_anio,trimestre,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz,anio_semana
1,2022-07-13,17128,890-122,2.0,A,890,Nueva Distribución,2022,7,28,3,17128,ESPAÑA,BURGOS,BURGOS,UE,CruzND,2022-28
4,2024-01-15,60000,012-086,1.0,A,12,Nueva Distribución,2024,1,3,1,60000,ESPAÑA,NaN,NaN,UE,UsuarioCR,2024-3
5,2024-07-30,60000,012-050,2.0,B,12,Nueva Distribución,2024,7,31,3,60000,ESPAÑA,NaN,NaN,UE,UsuarioCR,2024-31
6,2023-09-26,60216,012-114,1.0,A,12,Nueva Distribución,2023,9,39,3,60216,ESPAÑA,MARBELLA,MALAGA,UE,UsuarioCR,2023-39
7,2024-07-30,60000,012-070,2.0,A,12,Nueva Distribución,2024,7,31,3,60000,ESPAÑA,NaN,NaN,UE,UsuarioCR,2024-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597114,2022-02-03,11117,923-064,1.0,A,923SF,Tradicional,2022,2,5,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2022-5
597115,2022-01-13,11117,921-936,1.0,B,921SR,Tradicional,2022,1,2,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2022-2
597117,2022-03-01,11117,921-310,1.0,A,921S,Tradicional,2022,3,9,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2022-9
597121,2022-01-13,11117,933-071,1.0,A,933,Tradicional,2022,1,2,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2022-2
597366,2022-03-01,11117,925-773,1.0,A,924A,Tradicional,2022,3,9,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2022-9

In [74]:
#Creamos el primer dataset para el modelo agupando por anio_semana, codigo_articulo, provincia y tipo_abc
df_agrupado=df_base.groupby(['anio_semana','Provincia','tipo_abc','codigo_articulo'])['unidades'].sum().reset_index()
df_agrupado

       anio_semana Provincia tipo_abc codigo_articulo  unidades
0           2022-1  A CORUÑA        A         012-226       1.0
1           2022-1  A CORUÑA        A         921-310       1.0
2           2022-1  A CORUÑA        A         921-375       2.0
3           2022-1  A CORUÑA        A         924-793       1.0
4           2022-1  A CORUÑA        A         925-701       1.0
...            ...       ...      ...             ...       ...
221504      2024-9  ZARAGOZA        B         935-924       1.0
221505      2024-9  ZARAGOZA        B         940-705       1.0
221506      2024-9  ZARAGOZA        C         930-800       1.0
221507      2024-9  ZARAGOZA        C         932-043       1.0
221508      2024-9  ZARAGOZA        C         936-597       1.0

[221509 rows x 5 columns]

In [75]:
provincias_unicas = df_base['Provincia'].unique()
print(provincias_unicas)

['BURGOS' nan 'MALAGA' 'MADRID' 'SEVILLA' 'HUESCA' 'BADAJOZ'
 'STA CRUZ DE TENERIFE' 'PONTEVEDRA' 'CORDOBA' 'NAVARRA' 'LLEIDA'
 'CIUDAD REAL' 'ALICANTE' 'MURCIA' 'BARCELONA' 'A CORUÑA' 'JAEN'
 'ALBACETE' 'ZARAGOZA' 'CASTELLON' 'GIRONA' 'TERUEL' 'VIZCAYA' 'CADIZ'
 'ZAMORA' 'ASTURIAS' 'LUGO' 'TARRAGONA' 'LEON' 'OURENSE' 'CACERES'
 'CANTABRIA' 'GRANADA' 'TOLEDO' 'GIPUZKOA' 'VALLADOLID' 'HUELVA'
 'LAS PALMAS' 'ALAVA' 'ALMERIA' 'VALENCIA' 'CEUTA' 'LA RIOJA'
 'ILLES BALEARS' 'SALAMANCA' 'SEGOVIA' 'AVILA' 'GUADALAJARA' 'CUENCA'
 'SORIA' 'PALENCIA' 'MELILLA' 'Málaga']

In [76]:
df_ciclismo

,Fecha Prueba,Año Prueba,Semana,Ano_Semana,Fecha fin,Duración(Dias),Modalidad,Provincia,Lugar
0,02/01/2022,2022,52,2022-52,02/01/2022,1,CicloCross,BARCELONA,EL BRUC
1,02/01/2022,2022,52,2022-52,02/01/2022,1,CicloCross,GIPUZKOA,ORMAIZTEGI
2,02/01/2022,2022,52,2022-52,02/01/2022,1,CicloCross,CANTABRIA,LOS CORRALES DE BUELNA
3,07/01/2022,2022,1,2022-1,09/01/2022,3,CicloCross,VALENCIA,XATIVA
4,15/01/2022,2022,2,2022-2,15/01/2022,1,Pista,ILLES BALEARS,PALMA DE MALLORCA
...,...,...,...,...,...,...,...,...,...
2244,28/12/2024,2024,52,2024-52,28/12/2024,1,CicloCross,PONTEVEDRA,NIGRAN
2245,28/12/2024,2024,52,2024-52,28/12/2024,1,CicloCross,CASTELLON,CERVERA DEL MAESTRE
2246,29/12/2024,2024,52,2024-52,29/12/2024,1,CicloCross,GIRONA,VILABLAREIX
2247,29/12/2024,2024,52,2024-52,29/12/2024,1,CicloCross,CASTELLON,BURRIANA
2248,29/12/2024,2024,52,2024-52,29/12/2024,1,CicloCross,MADRID,PARLA

## Estandarizamos los nombres de las provincias para cruzar los dataframes

In [77]:
set_agrupado = set(df_agrupado['Provincia'].unique())
set_ciclismo = set(df_ciclismo['Provincia'].unique())

# Provincias que están en ciclismo pero faltan en tu tabla agrupada
print("Faltan en df_agrupado:", set_ciclismo - set_agrupado)

# Provincias que sobran en agrupado o están escritas distinto
print("Faltan en df_ciclismo:", set_agrupado - set_ciclismo)

Faltan en df_agrupado: {'A CORUNA'}
Faltan en df_ciclismo: {'Málaga', 'A CORUÑA'}

In [78]:
import unicodedata

def limpiar_texto(texto):
    if pd.isna(texto): return texto
    # Normalizar para separar caracteres de tildes
    texto = unicodedata.normalize('NFD', str(texto))
    # Filtrar solo caracteres que no sean tildes, pasar a mayúsculas y quitar espacios
    return "".join(c for c in texto if unicodedata.category(c) != 'Mn').upper().strip()

# Aplicar limpieza a la columna Provincia en ambos DataFrames
df_agrupado['Provincia'] = df_agrupado['Provincia'].apply(limpiar_texto)
df_ciclismo['Provincia'] = df_ciclismo['Provincia'].apply(limpiar_texto)

In [79]:
# Buscar filas en ciclismo cuya provincia no exista en el agrupado
invalidas = df_ciclismo[~df_ciclismo['Provincia'].isin(df_agrupado['Provincia'])]

if invalidas.empty:
    print("✅ ¡Perfecto! Todas las provincias de df_ciclismo existen en df_agrupado.")
else:
    print(f"⚠️ Atención: Hay {invalidas['Provincia'].nunique()} nombres que aún no coinciden.")
    print(invalidas['Provincia'].unique())

✅ ¡Perfecto! Todas las provincias de df_ciclismo existen en df_agrupado.

In [80]:
# Definimos la traducción: 'Valor_en_ciclismo': 'Valor_en_agrupado'
mapeo_provincias = {
    'BALEARES': 'ILLES BALEARS',
    'S.C TENERIFE': 'STA CRUZ DE TENERIFE',
    'BIZKAIA': 'VIZCAYA'
}

# Aplicamos el cambio solo en df_ciclismo
df_ciclismo['Provincia'] = df_ciclismo['Provincia'].replace(mapeo_provincias)

# Volvemos a verificar
invalidas = df_ciclismo[~df_ciclismo['Provincia'].isin(df_agrupado['Provincia'])]

if invalidas.empty:
    print("✅ ¡Conseguido! Ahora todos los nombres coinciden.")
else:
    print(f"Aún quedan: {invalidas['Provincia'].unique()}")

✅ ¡Conseguido! Ahora todos los nombres coinciden.

In [81]:
display(df_agrupado)
display(df_ciclismo)

       anio_semana Provincia tipo_abc codigo_articulo  unidades
0           2022-1  A CORUNA        A         012-226       1.0
1           2022-1  A CORUNA        A         921-310       1.0
2           2022-1  A CORUNA        A         921-375       2.0
3           2022-1  A CORUNA        A         924-793       1.0
4           2022-1  A CORUNA        A         925-701       1.0
...            ...       ...      ...             ...       ...
221504      2024-9  ZARAGOZA        B         935-924       1.0
221505      2024-9  ZARAGOZA        B         940-705       1.0
221506      2024-9  ZARAGOZA        C         930-800       1.0
221507      2024-9  ZARAGOZA        C         932-043       1.0
221508      2024-9  ZARAGOZA        C         936-597       1.0

[221509 rows x 5 columns]

,Fecha Prueba,Año Prueba,Semana,Ano_Semana,Fecha fin,Duración(Dias),Modalidad,Provincia,Lugar
0,02/01/2022,2022,52,2022-52,02/01/2022,1,CicloCross,BARCELONA,EL BRUC
1,02/01/2022,2022,52,2022-52,02/01/2022,1,CicloCross,GIPUZKOA,ORMAIZTEGI
2,02/01/2022,2022,52,2022-52,02/01/2022,1,CicloCross,CANTABRIA,LOS CORRALES DE BUELNA
3,07/01/2022,2022,1,2022-1,09/01/2022,3,CicloCross,VALENCIA,XATIVA
4,15/01/2022,2022,2,2022-2,15/01/2022,1,Pista,ILLES BALEARS,PALMA DE MALLORCA
...,...,...,...,...,...,...,...,...,...
2244,28/12/2024,2024,52,2024-52,28/12/2024,1,CicloCross,PONTEVEDRA,NIGRAN
2245,28/12/2024,2024,52,2024-52,28/12/2024,1,CicloCross,CASTELLON,CERVERA DEL MAESTRE
2246,29/12/2024,2024,52,2024-52,29/12/2024,1,CicloCross,GIRONA,VILABLAREIX
2247,29/12/2024,2024,52,2024-52,29/12/2024,1,CicloCross,CASTELLON,BURRIANA
2248,29/12/2024,2024,52,2024-52,29/12/2024,1,CicloCross,MADRID,PARLA

In [82]:
# 1. Preparamos df_ciclismo: solo columnas necesarias y renombramos la clave del tiempo
df_ciclismo_sub = df_ciclismo[['Ano_Semana', 'Provincia', 'Duración(Dias)', 'Modalidad']].copy()
df_ciclismo_sub.columns = ['anio_semana', 'Provincia', 'duracion', 'modalidad']

# 2. Hacemos el MERGE (Left Join)
# Esto mantiene todas las filas de df_agrupado y añade info de ciclismo donde coincida
df_final = pd.merge(
    df_agrupado, 
    df_ciclismo_sub, 
    on=['anio_semana', 'Provincia'], 
    how='left'
)

# 3. Crear la columna adicional (1 si hay prueba, 0 si no)
# Si 'modalidad' es NaN, significa que no hubo coincidencia (no hay prueba)
df_final['hay_prueba'] = df_final['modalidad'].notna().astype(int)

# 4. (Opcional) Limpiar los NaN en duracion y modalidad para que se vea mejor
df_final['duracion'] = df_final['duracion'].fillna(0)
df_final['modalidad'] = df_final['modalidad'].fillna('Sin prueba')

df_final

,anio_semana,Provincia,tipo_abc,codigo_articulo,unidades,duracion,modalidad,hay_prueba
0,2022-1,A CORUNA,A,012-226,1.0,0.0,Sin prueba,0
1,2022-1,A CORUNA,A,921-310,1.0,0.0,Sin prueba,0
2,2022-1,A CORUNA,A,921-375,2.0,0.0,Sin prueba,0
3,2022-1,A CORUNA,A,924-793,1.0,0.0,Sin prueba,0
4,2022-1,A CORUNA,A,925-701,1.0,0.0,Sin prueba,0
...,...,...,...,...,...,...,...,...
260403,2024-9,ZARAGOZA,B,935-924,1.0,0.0,Sin prueba,0
260404,2024-9,ZARAGOZA,B,940-705,1.0,0.0,Sin prueba,0
260405,2024-9,ZARAGOZA,C,930-800,1.0,0.0,Sin prueba,0
260406,2024-9,ZARAGOZA,C,932-043,1.0,0.0,Sin prueba,0
260407,2024-9,ZARAGOZA,C,936-597,1.0,0.0,Sin prueba,0

## Leemos datos de Clima

In [83]:
# Leer el dataset de clima
df_clima = pd.read_csv('../Datasets/clima_semanal_openmeteo.csv')

# 1. Filtrar el rango específico: 2022, 2023 y 2024
df_clima_filtrado = df_clima[df_clima['year'].isin([2022, 2023, 2024])].copy()

# 2. Estandarizar provincias y crear la llave de unión
# (Asegúrate de haber ejecutado la función limpiar_texto previamente)
df_clima_filtrado['provincia'] = df_clima_filtrado['provincia'].apply(limpiar_texto)
df_clima_filtrado['anio_semana'] = df_clima_filtrado['year'].astype(str) + '-' + df_clima_filtrado['semana'].astype(str)

# 3. Agrupar por semana y provincia con las métricas solicitadas
df_clima_agrupado = df_clima_filtrado.groupby(['anio_semana', 'provincia']).agg({
    'temp_media': 'mean',
    'precip_mm': 'mean',
    'viento_max': 'mean'
}).reset_index()

# 4. Renombrar para que el Merge sea limpio
df_clima_agrupado.columns = ['anio_semana', 'Provincia', 'temp_media_sem', 'precip_media_sem', 'viento_max_medio_sem']

# Verificación de los años resultantes
print(f"Años en el dataset de clima: {sorted(df_clima_filtrado['year'].unique())}")
display(df_clima_agrupado.head())

Años en el dataset de clima: [np.int64(2022), np.int64(2023), np.int64(2024)]

,anio_semana,Provincia,temp_media_sem,precip_media_sem,viento_max_medio_sem
0,2022-1,A CORUNA,11.67,62.0,38.5
1,2022-1,ALAVA,6.36,54.5,25.8
2,2022-1,ALBACETE,5.69,2.3,27.3
3,2022-1,ALICANTE,12.10,0.0,49.8
4,2022-1,ALMERIA,12.33,1.3,32.6

In [84]:
# 1. Aseguramos que los nombres de las columnas en el filtrado sean los correctos
# Creamos 'Provincia' (mayúscula) a partir de 'provincia' (minúscula)
df_clima_filtrado['Provincia'] = df_clima_filtrado['provincia'].apply(limpiar_texto)

# 2. Ahora sí, agrupamos usando 'Provincia' con P mayúscula
df_clima_agrupado = df_clima_filtrado.groupby(['anio_semana', 'Provincia']).agg({
    'temp_media': 'mean',
    'precip_mm': 'mean',
    'viento_max': 'mean'
}).reset_index()

# 3. Renombramos las columnas finales
df_clima_agrupado.columns = [
    'anio_semana', 
    'Provincia', 
    'clima_temp_media', 
    'clima_precip_media', 
    'clima_viento_max_medio'
]

display(df_clima_agrupado.head())

,anio_semana,Provincia,clima_temp_media,clima_precip_media,clima_viento_max_medio
0,2022-1,A CORUNA,11.67,62.0,38.5
1,2022-1,ALAVA,6.36,54.5,25.8
2,2022-1,ALBACETE,5.69,2.3,27.3
3,2022-1,ALICANTE,12.10,0.0,49.8
4,2022-1,ALMERIA,12.33,1.3,32.6

In [85]:
display(df_final)

,anio_semana,Provincia,tipo_abc,codigo_articulo,unidades,duracion,modalidad,hay_prueba
0,2022-1,A CORUNA,A,012-226,1.0,0.0,Sin prueba,0
1,2022-1,A CORUNA,A,921-310,1.0,0.0,Sin prueba,0
2,2022-1,A CORUNA,A,921-375,2.0,0.0,Sin prueba,0
3,2022-1,A CORUNA,A,924-793,1.0,0.0,Sin prueba,0
4,2022-1,A CORUNA,A,925-701,1.0,0.0,Sin prueba,0
...,...,...,...,...,...,...,...,...
260403,2024-9,ZARAGOZA,B,935-924,1.0,0.0,Sin prueba,0
260404,2024-9,ZARAGOZA,B,940-705,1.0,0.0,Sin prueba,0
260405,2024-9,ZARAGOZA,C,930-800,1.0,0.0,Sin prueba,0
260406,2024-9,ZARAGOZA,C,932-043,1.0,0.0,Sin prueba,0
260407,2024-9,ZARAGOZA,C,936-597,1.0,0.0,Sin prueba,0

In [86]:
# 1. Obtener la lista de semanas únicas que realmente existen en tus ventas
semanas_ventas = df_final['anio_semana'].unique()

# 2. Preparar el clima (Asegúrate de tener cargado df_clima)
# Creamos la llave anio_semana con el mismo formato (sin ceros a la izquierda)
df_clima['anio_semana'] = df_clima['year'].astype(str) + '-' + df_clima['semana'].astype(str)

# 3. Filtrar el clima para que SOLO tenga las semanas que hay en las ventas
# Esto asegura que el horizonte temporal sea idéntico (2022-1 hasta 2024-39)
df_clima_sincronizado = df_clima[df_clima['anio_semana'].isin(semanas_ventas)].copy()

# 4. Limpiar provincias para asegurar el match
df_clima_sincronizado['Provincia'] = df_clima_sincronizado['provincia'].apply(limpiar_texto)

# 5. Agrupar por el mismo horizonte
df_clima_agrupado = df_clima_sincronizado.groupby(['anio_semana', 'Provincia']).agg({
    'temp_media': 'mean',
    'precip_mm': 'mean',
    'viento_max': 'mean'
}).reset_index()

# 6. Renombrar columnas
df_clima_agrupado.columns = [
    'anio_semana', 
    'Provincia', 
    'clima_temp_media', 
    'clima_precip_media', 
    'clima_viento_max_medio'
]

# Verificación final
print(f"Semanas en ventas: {len(semanas_ventas)}")
print(f"Semanas en clima: {df_clima_agrupado['anio_semana'].nunique()}")
display(df_clima_agrupado.head())

Semanas en ventas: 143
Semanas en clima: 143

,anio_semana,Provincia,clima_temp_media,clima_precip_media,clima_viento_max_medio
0,2022-1,A CORUNA,11.67,62.0,38.5
1,2022-1,ALAVA,6.36,54.5,25.8
2,2022-1,ALBACETE,5.69,2.3,27.3
3,2022-1,ALICANTE,12.10,0.0,49.8
4,2022-1,ALMERIA,12.33,1.3,32.6

In [87]:
# Limpieza de seguridad de última hora
df_final['Provincia'] = df_final['Provincia'].astype(str).str.strip()
df_final['anio_semana'] = df_final['anio_semana'].astype(str).str.strip()

df_clima_agrupado['Provincia'] = df_clima_agrupado['Provincia'].astype(str).str.strip()
df_clima_agrupado['anio_semana'] = df_clima_agrupado['anio_semana'].astype(str).str.strip()

In [88]:
# 1. Diccionario para unificar nombres entre Clima y Ventas
mapeo_clima_nombres = {
    'GUIPUZCOA': 'GIPUZKOA',
    'SANTA CRUZ DE TENERIFE': 'STA CRUZ DE TENERIFE',
    'BIZKAIA':'VIZCAYA'
}

# 2. Limpieza profunda del Clima antes de agrupar
df_clima['Provincia'] = df_clima['provincia'].apply(limpiar_texto)
df_clima['Provincia'] = df_clima['Provincia'].replace(mapeo_clima_nombres)
df_clima['anio_semana'] = df_clima['year'].astype(str) + '-' + df_clima['semana'].astype(str)

# 3. Agrupación (Asegurando que no hay espacios en las llaves)
df_clima_agrupado = df_clima[df_clima['year'].isin([2022, 2023, 2024])].groupby(['anio_semana', 'Provincia']).agg({
    'temp_media': 'mean',
    'precip_mm': 'mean',
    'viento_max': 'mean'
}).reset_index()

df_clima_agrupado.columns = ['anio_semana', 'Provincia', 'clima_temp', 'clima_precip', 'clima_viento']

# 4. LIMPIEZA CRÍTICA: Quitar espacios en blanco invisibles en AMBAS tablas
df_final['Provincia'] = df_final['Provincia'].astype(str).str.strip()
df_final['anio_semana'] = df_final['anio_semana'].astype(str).str.strip()
df_clima_agrupado['Provincia'] = df_clima_agrupado['Provincia'].astype(str).str.strip()
df_clima_agrupado['anio_semana'] = df_clima_agrupado['anio_semana'].astype(str).str.strip()

# 5. MERGE FINAL
df_maestro = pd.merge(df_final, df_clima_agrupado, on=['anio_semana', 'Provincia'], how='left')

# Verificación
print(f"¿Quedan nulos en A CORUNA?: {df_maestro[df_maestro['Provincia']=='A CORUNA']['clima_temp'].isna().sum()}")
display(df_maestro.head())

¿Quedan nulos en A CORUNA?: 0

,anio_semana,Provincia,tipo_abc,codigo_articulo,unidades,duracion,modalidad,hay_prueba,clima_temp,clima_precip,clima_viento
0,2022-1,A CORUNA,A,012-226,1.0,0.0,Sin prueba,0,11.67,62.0,38.5
1,2022-1,A CORUNA,A,921-310,1.0,0.0,Sin prueba,0,11.67,62.0,38.5
2,2022-1,A CORUNA,A,921-375,2.0,0.0,Sin prueba,0,11.67,62.0,38.5
3,2022-1,A CORUNA,A,924-793,1.0,0.0,Sin prueba,0,11.67,62.0,38.5
4,2022-1,A CORUNA,A,925-701,1.0,0.0,Sin prueba,0,11.67,62.0,38.5

In [89]:
#1. Aseguramos la función de limpieza (por si acaso)
def limpiar_texto(texto):
    if pd.isna(texto): return texto
    texto = unicodedata.normalize('NFD', str(texto))
    return "".join(c for c in texto if unicodedata.category(c) != 'Mn').upper().strip()

# 2. Diccionario de traducción para que el clima hable el mismo idioma que ventas
mapeo_clima = {
    'GUIPUZCOA': 'GIPUZKOA',
    'SANTA CRUZ DE TENERIFE': 'STA CRUZ DE TENERIFE'
}

# 3. Preparar df_clima_agrupado desde cero con correcciones
df_clima_filt = df_clima[df_clima['year'].isin([2022, 2023, 2024])].copy()
df_clima_filt['Provincia'] = df_clima_filt['provincia'].apply(limpiar_texto).replace(mapeo_clima)
df_clima_filt['anio_semana'] = df_clima_filt['year'].astype(str) + '-' + df_clima_filt['semana'].astype(str)

df_clima_agrupado = df_clima_filt.groupby(['anio_semana', 'Provincia']).agg({
    'temp_media': 'mean',
    'precip_mm': 'mean',
    'viento_max': 'mean'
}).reset_index()

df_clima_agrupado.columns = ['anio_semana', 'Provincia', 'clima_temp', 'clima_precip', 'clima_viento']

# 4. LIMPIEZA DE SEGURIDAD: Quitamos cualquier espacio invisible en ambos DataFrames
df_final['Provincia'] = df_final['Provincia'].astype(str).str.strip()
df_final['anio_semana'] = df_final['anio_semana'].astype(str).str.strip()

df_clima_agrupado['Provincia'] = df_clima_agrupado['Provincia'].astype(str).str.strip()
df_clima_agrupado['anio_semana'] = df_clima_agrupado['anio_semana'].astype(str).str.strip()

# 5. EL MERGE FINAL
df_maestro = pd.merge(df_final, df_clima_agrupado, on=['anio_semana', 'Provincia'], how='left')

# Verificación de resultados
print(f"Total filas: {len(df_maestro)}")
print(f"Nulos en A CORUNA: {df_maestro[df_maestro['Provincia'] == 'A CORUNA']['clima_temp'].isna().sum()}")
display(df_maestro.head())

Total filas: 260408
Nulos en A CORUNA: 0

,anio_semana,Provincia,tipo_abc,codigo_articulo,unidades,duracion,modalidad,hay_prueba,clima_temp,clima_precip,clima_viento
0,2022-1,A CORUNA,A,012-226,1.0,0.0,Sin prueba,0,11.67,62.0,38.5
1,2022-1,A CORUNA,A,921-310,1.0,0.0,Sin prueba,0,11.67,62.0,38.5
2,2022-1,A CORUNA,A,921-375,2.0,0.0,Sin prueba,0,11.67,62.0,38.5
3,2022-1,A CORUNA,A,924-793,1.0,0.0,Sin prueba,0,11.67,62.0,38.5
4,2022-1,A CORUNA,A,925-701,1.0,0.0,Sin prueba,0,11.67,62.0,38.5

In [92]:
# 1. Creamos un diccionario de "vecinos"
vecinos = {
    'VIZCAYA': 'GIPUZKOA',
    'CEUTA': 'CADIZ',
    'MELILLA': 'MALAGA'
}

# 2. Iteramos para rellenar los huecos
for prov_nula, prov_vecina in vecinos.items():
    # Extraemos el clima de la provincia vecina
    clima_vecino = df_clima_agrupado[df_clima_agrupado['Provincia'] == prov_vecina].copy()
    clima_vecino['Provincia'] = prov_nula # Le cambiamos el nombre para que coincida
    
    # Actualizamos los nulos en df_maestro usando los datos del vecino
    df_maestro.update(
        df_maestro[df_maestro['Provincia'] == prov_nula].merge(
            clima_vecino, on=['anio_semana', 'Provincia'], suffixes=('_old', '')
        ).set_index(df_maestro[df_maestro['Provincia'] == prov_nula].index)
    )

print("✅ Clima de Vizcaya, Ceuta y Melilla completado usando provincias vecinas.")

✅ Clima de Vizcaya, Ceuta y Melilla completado usando provincias vecinas.

In [ ]:
df_maestro.isna().sum()

anio_semana        0
Provincia          0
tipo_abc           0
codigo_articulo    0
unidades           0
duracion           0
modalidad          0
hay_prueba         0
clima_temp         0
clima_precip       0
clima_viento       0
dtype: int64

In [96]:
df_maestro.to_csv('df_maestro_final.csv', index=False, encoding='utf-8-sig')